# grafana-values.yaml

replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.default.svc.cluster.local
        isDefault: true
        editable: true

